from arpeggio import PTNodeVisitor


class CodeGenerationVisitor(PTNodeVisitor):

    WAT_TEMPLATE = ''';; Code generated by the Delta compiler
(module
  (func
    (export "_start")
    (result i32)
{}{}  )
)
'''

    def __init__(self, symbol_table, **kwargs):
        super().__init__(**kwargs)
        self.__symbol_table = symbol_table

    def visit_program_start(self, node, children):

        def var_decl():
            return ''.join([f'    (local ${var} i32)\n'
                            for var in self.__symbol_table])

        return CodeGenerationVisitor.WAT_TEMPLATE.format(
            var_decl(), ''.join(children))

    def visit_expression_start(self, _, children):
        return CodeGenerationVisitor.WAT_TEMPLATE.format('', children[0])

    def visit_expression(self, _, children):
        result = [children[0]]
        for i in range(1, len(children), 2):
            result.append(children[i + 1])
            match children[i]:
                case '+':
                    result.append('    i32.add\n')
                case '-':
                    result.append('    i32.sub\n')
        return ''.join(result)

    def visit_multiplication(self, _, children):
        result = [children[0]]
        for i in range(1, len(children), 2):
            result.append(children[i + 1])
            match children[i]:
                case '*':
                    result.append('    i32.mul\n')
                case '/':
                    result.append('    i32.div_s\n')
                case '%':
                    result.append('    i32.rem_s\n')
        return ''.join(result)

    def visit_unary(self, node, children):
        result = children[-1]
        for i in children[-2::-1]:
            match i:
                case '+':
                    ...  # do nothing
                case '-':
                    result = (
                        '    i32.const 0\n'
                        + result
                        + '    i32.sub\n')
                case '!':
                    result += '    i32.eqz\n'
        return result

    def visit_primary(self, _, children):
        return children[0]

    def visit_decimal(self, node, _):
        return f'    i32.const {node.value}\n'

    def visit_boolean(self, _, children):
        if children[0] == 'true':
            return f'    i32.const 1\n'
        else:
            return f'    i32.const 0\n'

    def visit_parenthesis(self, _, children):
        return children[0]

    def visit_rhs_variable(self, node, _):
        return f'    local.get ${node.value}\n'

    def visit_declaration(self, node, _):
        return ''

    def visit_assignment(self, _, children):
        return children[1] + children[0]

    def visit_statement(self, _, children):
        return children[0]

    def visit_lhs_variable(self, node, _):
        return f'    local.set ${node.value}\n'

    def visit_block(self, _, children):
        return ''.join(children)

    def visit_if(self, _, children):
        result = children[0] + '    if\n' + children[1] + '    else\n'
        if len(children) == 3:
            result += children[2]
        result += '    end\n'
        return result

    def visit_while(self, _, children):
        return ('    block\n'
                + '    loop\n'
                + children[0]
                + '    i32.eqz\n'
                + '    br_if 1\n'
                + children[1]
                + '    br 0\n'
                + '    end\n'
                + '    end\n')

    def visit_for(self, node, children):
        loop_var, start, direction, finish, body = children
        if direction == 'upto':
            comparison = '    i32.gt_s\n'
            step = '    i32.add\n'
        else:
            comparison = '    i32.lt_s\n'
            step = '    i32.sub\n'
        return (
            start
            + f'    local.set ${loop_var}\n'
            + '    block\n'
            + '    loop\n'
            + f'    local.get ${loop_var}\n'
            + finish
            + comparison
            + '    br_if 1\n'
            + body
            + f'    local.get ${loop_var}\n'
            + '    i32.const 1\n'
            + step
            + f'    local.set ${loop_var}\n'
            + '    br 0\n'
            + '    end\n'
            + '    end\n')

    def visit_for_variable(self, node, _):
        return node.value
